# Builds docker images.
version: "3.3"
services:
  nginx-frontend:
    image: roysalazarportilla/portfolio_bug-tracker_nginx-frontend:latest
    build:
      context: ./frontend/nginx
      dockerfile: Dockerfile
    container_name: nginx-frontend
  frontend:
    image: roysalazarportilla/portfolio_bug-tracker_frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
  backend:
    image: roysalazarportilla/portfolio_bug-tracker_backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
  database:
    image: roysalazarportilla/portfolio_bug-tracker_database:latest
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: database