version: "3.3"
services:
  nginx:
    depends_on:
      - frontend
      - backend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    volumes:
      - ./nginx/configs/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
    restart: on-failure
    container_name: frontend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
    restart: on-failure
    container_name: backend