# Builds docker images.
version: "3.3"
services:
  nginx:
    image: roysalazarportilla/bug-tracker-nginx:latest
    build:
      dockerfile: Dockerfile
      context: ./nginx
    container_name: nginx
  frontend:
    image: roysalazarportilla/bug-tracker-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
  backend:
    image: roysalazarportilla/bug-tracker-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend