version: "3.3"
services:  
  frontend-unit-tests:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
  backend-unit-tests:
    build:
      context: ./backend
      dockerfile: Dockerfile.test