version: "3.3"
services:
  portfolio_bug-tracker_nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    volumes:
      - ./nginx/configs/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    container_name: portfolio_bug-tracker_nginx
    networks:
      - portfolio-network
  portfolio_bug-tracker_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/.next
      - /app/node_modules
    restart: on-failure
    env_file:
      - ./dev-env/frontend.env
    container_name: portfolio_bug-tracker_frontend
    networks:
      - portfolio-network
  portfolio_bug-tracker_backend:
    depends_on:
      - portfolio_bug-tracker_database
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3001'
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
    restart: on-failure
    container_name: portfolio_bug-tracker_backend
    env_file:
      - ./dev-env/backend.env
      - ./dev-env/database.env
    networks:
      - portfolio-network
  portfolio_bug-tracker_database:
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: on-failure
    # Persist db data
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
    container_name: portfolio_bug-tracker_database
    env_file:
      - ./dev-env/database.env
    networks:
      - portfolio-network
networks:
  portfolio-network:
    external: true