version: "3.3"
services:  
  portfolio_bug-tracker_frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev.test
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always
    env_file:
      - ./dev-env/frontend.env
    container_name: portfolio_bug-tracker_frontend-test
  portfolio_bug-tracker_backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev.test
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
    restart: always
    container_name: portfolio_bug-tracker_backend-test
    env_file:
      - ./dev-env/backend.env