version: "3.3"
services:  
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    volumes:
      - ./nginx/configs/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    container_name: nginx
    networks:
      - portfolio-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/.next
      - /app/node_modules
    # ports:
    #   - '8080:8080'
    restart: on-failure
    env_file:
      - ./dev-env/frontend.env
    container_name: frontend
    networks:
      - portfolio-network
  backend:
    depends_on:
      - database
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3001'
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
    restart: on-failure
    container_name: backend
    env_file:
      - ./dev-env/backend.env
      - ./dev-env/database.env
    networks:
      - portfolio-network
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: on-failure
    # Persist db data
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
    container_name: database
    env_file:
      - ./dev-env/database.env
    networks:
      - portfolio-network
networks:
  portfolio-network:
    external: true