# Runs docker images from docker hub repository.
version: "3.3"
services:
  portfolio_bug-tracker_nginx-frontend:
    image: roysalazarportilla/portfolio_bug-tracker_nginx-frontend:latest
    restart: on-failure
    container_name: portfolio_bug-tracker_nginx-frontend
    networks:
      - portfolio-network
  portfolio_bug-tracker_frontend:
    image: roysalazarportilla/portfolio_bug-tracker_frontend:latest
    restart: on-failure
    env_file:
      - /etc/environment
    container_name: portfolio_bug-tracker_frontend
    networks:
      - portfolio-network
  portfolio_bug-tracker_backend:
    image: roysalazarportilla/portfolio_bug-tracker_backend:latest
    restart: on-failure
    env_file:
      - /etc/environment
    container_name: portfolio_bug-tracker_backend
    networks:
      - portfolio-network
  portfolio_bug-tracker_database:
    image: roysalazarportilla/portfolio_bug-tracker_database:latest
    restart: on-failure
    # Persist db data
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
    env_file:
      - /etc/environment
    container_name: portfolio_bug-tracker_database
    networks:
      - portfolio-network
networks:
  portfolio-network:
    external: true