# Runs docker images from docker hub repository.
version: "3.3"
services:
  nginx:
    image: roysalazarportilla/bug-tracker-nginx:latest
    depends_on:
      - frontend
      - backend
    restart: always
    ports:
      - '80:80'
  frontend:
    image: roysalazarportilla/bug-tracker-frontend:latest
    restart: on-failure
    env_file:
      - /etc/environment
    container_name: frontend
  backend:
    image: roysalazarportilla/bug-tracker-backend:latest
    restart: on-failure
    env_file:
      - /etc/environment
    container_name: backend
  database:
    image: roysalazarportilla/bug-tracker-database:latest
    restart: on-failure
    # Persist db data
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
    env_file:
      - /etc/environment
    container_name: database