# Runs docker images from docker hub repository.
version: "3.3"
services:
  frontend:
    image: roysalazarportilla/portfolio_bug-tracker_frontend:latest
    restart: on-failure
    env_file:
      - /etc/environment
    container_name: frontend
    networks:
      - portfolio-network
  backend:
    image: roysalazarportilla/portfolio_bug-tracker_backend:latest
    restart: on-failure
    env_file:
      - /etc/environment
    container_name: backend
    networks:
      - portfolio-network
  database:
    image: roysalazarportilla/portfolio_bug-tracker_database:latest
    restart: on-failure
    # Persist db data
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
    env_file:
      - /etc/environment
    container_name: database
    networks:
      - portfolio-network
networks:
  portfolio-network:
    external: true