name: cicd
on: 
  push: 
    branches: 
      - 'main'

jobs: 
  cicd:
    name: CI/CD
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v3

      - name: Run unit tests
        run: | 
          chmod +x ./test.sh
          ./test.sh

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push containers to Docker Hub
        run: | 
          chmod +x ./deploy.sh
          ./deploy.sh